### ISSUE TITLE
Change `UseGlitter` to `AddGlitter`.

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/Glitter#39]
### 🐛 Category

😖 Other

### 🔢 Version

🐣 Pre-Release

### 🤔 What's hapening?

It's standard practice to use the `AddX` naming convention when extending `IServiceCollection` to simplify adding services to the DI container. Currently Glitter is added with `.UseGlitter` which doesn't follow this convention.

### 📝 What was your expectation?

Change the `UseGlitter` extension to `AddGlitter`.

**Comment by Adhityanarayan** [comment]
Hello @tacosontitan , I'm a beginner to open source and I'd like to work on this. I am excited to contribute and am looking forward to learning more about this project. Thank you for considering my involvement.

**Comment by tacosontitan** [comment]
@Adhityanarayan, I've assigned the issue to you :) thank you for offering to help the project out!

**Comment by Adhityanarayan** [comment]
#56
